name:

on: push

jobs:
  markdown-to-pdf:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # We use `git describe` which requires tags
        with:
          fetch-depth: 0
      - name: "Install pandoc"
        shell: bash
        run: |
          mkdir -p usr/bin
          wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-linux-amd64.tar.gz -O - | tar -zx -C usr/bin --strip-components 2
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.17.0/pandoc-crossref-Linux.tar.xz -O - | tar -Jx -C usr/bin
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH
      - name: "Check Formatting"
        shell: bash
        run: |
          make format
          if ! git diff --quiet; then
            echo 'Please run `make format` on your change to apply the following formatting fixes:' >> $GITHUB_STEP_SUMMARY
            echo '```diff' >> $GITHUB_STEP_SUMMARY
            git diff >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - name: "Install TeX Live"
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install graphviz latexmk texlive-latex-extra texlive-latex-recommended texlive-font-utils
      - name: "Markdown -> [pandox] -> [TeXLive] -> PDF"
        run: make
      - name: "Upload build directory"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
      - name: "Create Release if Tagged"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            build/spec.pdf
            build/abi.pdf
