name: "Update Contributors"

on:
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: "Checkout chipsalliance/firrtl-spec"
        uses: actions/checkout@v3
      - name: "Update Contributors In-Place"
        shell: bash
        run: |
          ./scripts/get-contributors.sh -g ${{ secrets.GITHUB_TOKEN }} > include/contributors.json
      - name: "Open PR If New Contributors"
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci/update-contributors
          author: chiselbot <${{ chiselbot@users.noreply.github.com }}>
          committer: chiselbot <${{ chiselbot@users.noreply.github.com }}>
          reviewers: |
            seldridge
          title: Update Contributors
          body-path: Add missing contributors
          commit-message: Add missing contributors
